spring.datasource.url=jdbc:postgresql://localhost:5433/appdb 
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



#flei, 14.05: Port hard coded auf 5433, da auf der VM dieser Port korrekt ist